name: Send Confirmation Messages

on:
  schedule:
    - cron: '0 */3 * * *'  # Roda a cada 3 horas

jobs:
  send-confirmations:
    runs-on: ubuntu-latest
    steps:
      - name: Send Confirmation Messages
        run: |
          curl -X POST '${{ secrets.SUPABASE_FUNCTION_URL }}/send-confirmation' \
          -H 'Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}' \
          -H 'Content-Type: application/json' 